"""initial schema

Revision ID: 72f1840ca4f3
Revises: 
Create Date: 2026-09-02 21:25:24.947028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f1840ca4f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('job_url', sa.String(length=1024), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_mode', sa.Enum('ONSITE', 'HYBRID', 'REMOTE', 'UNKNOWN', name='workmode', native_enum=False), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('experience_min', sa.Float(), nullable=True),
    sa.Column('experience_max', sa.Float(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('preferred_skills', sa.JSON(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'STRONG', 'CONSIDER', 'LOW', 'SKIP', name='priority', native_enum=False), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('application_message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'SHORTLISTED', 'APPLY', 'APPLIED', 'REJECTED', 'INTERVIEW', 'OFFER', 'SKIPPED', 'DUPLICATE', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('recruiter_name', sa.String(length=255), nullable=True),
    sa.Column('recruiter_email', sa.String(length=255), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_url')
    )
    op.create_table('application_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_messages',
    sa.Column('gmail_message_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('extraction_failed', sa.Boolean(), nullable=False),
    sa.Column('raw_subject', sa.String(length=1024), nullable=True),
    sa.Column('raw_sender', sa.String(length=255), nullable=True),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('gmail_message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_messages')
    op.drop_table('application_events')
    op.drop_table('jobs')
    # ### end Alembic commands ###
